### DISCUSSION TITLE
Assertions / Test Framework

### DISCUSSION THREAD

**Discussion by rawkode** [comtrya/comtrya#62] [Ideas]
Below is an example assertion framework I'm considering for Comtrya. Comtrya is pretty difficult to test, and that's because it primarily integrates with other applications and testing that compatibility and correctness is painful.

I'd like to solve that in a way that can increase test-coverage for the project, and also give the users of Comtrya confidence that their manifests work.

The `actions` below aren't particularly important, what is important is the `assertions` key. The example below works well for a single OS, but fails when it comes to expanding. In this single OS example, there's 2 proposed formats. I only wish to accept one.

```yaml
actions:
  - action: command.run
    command: touch
    args:
      - $TMPDIR/cmd.run

  - action: command.run
    command: touch
    sudo: true
    args:
      - $TMPDIR/cmd.run.sudo

assertions:
  # LHS/RHS Format that can work for multiple assertion types
  - assert: command
    lhs: stat -f '%U' $TMPDIR/cmd.run
    rhs: 501
 
 - assert: net.port
    lhs: 80
    rhs: listening

  # Something less generic
  - command: stat -f '%U' $TMPDIR/cmd.run.sudo
    output: 0

  - net.port: 80
    status: listening
```

Then there's the cross OS assertions. How can I verify that my manifest works on Windows, macOS, and Linux? If we provide abstractions, we still run into the situation that we can't test those abstractions. Consider the following, they're essentially actions themselves.

```yaml
assertions:
  # Abstractions
  - assert: file.owned
    lhs: $TMPDIR/cmd.run
    rhs: 501

  # Abstractions
  - assert: package.installed
    lhs: chrome
    rhs: true
```

So I'm less keen on this. So considering filtering:

```yaml
  - assert: command
    lhs: stat -f '%U' $TMPDIR/cmd.run
    rhs: 501
    not: Windows

  - assert: command
    lhs: DIR $TMPDIR/cmd.run /Q
    rhs: Bill Gates
    only: Windows
```
