### DISCUSSION TITLE
Manifest Composition

### DISCUSSION THREAD

**Discussion by rawkode** [comtrya/comtrya#67] [Ideas]
Currently, you can compose manifests with other manifests using the dependency tree.

```yaml
# wrapper.yaml
depends:
- one
- two
```

I can then use `comtrya . -m wrapper` to run those grouped / composed manifests. 

I've also considered that some may not wish to throw around extra manifests for this kind of composition, and instead favour adding tags to their manifests and targeting them.

```yaml
tags:
- cli

- actions:
  - action: package.install
    name: git
```

Executed by `comtrya . -t cli`

Who's got opinions?
