### DISCUSSION TITLE
Not sure how to run run.yaml

### DISCUSSION THREAD

**Discussion by yiannis** [comtrya/comtrya#77] [Q&A] [answered]
Hello!

Sorry for the silly question, but I can't figure out how to run the simplest thing...
I have git cloned the repo and cargo build - all good.
Then I try to run one of the example files (`run.yaml`) and I get:

```
 % target/debug/comtrya examples/command 
  ERROR manifest_load{manifest="run.yaml"}: actions: missing field `dir` at line 2 column 3
```

Thanks

**Comment by rawkode** [comment, marked as answer]
Hey @yiannis !

Sorry, this is a bug. The `dir` parameter should be optional and it isn't. I'll get this fixed.

Here's an example

```yaml
actions:
  - action: command.run
    command: echo
    args: ["hi"]
    dir: .
```
