### ISSUE TITLE
Feature: run commands in an arbitrary git clone

### ISSUE THREAD

**Issue by mt-inside** [comtrya/comtrya#118]
Not all software installs nicely (via a package manager, or with `go install` / `cargo install`). I often find myself stringing together lots of `command.run` to:
* clone a repo, to a temp location
* cd into it
* run commands (`make build && sudo make install` kinda stuff)
* tidy up the clone.

It would be great to have an action like
```yaml
- action: command.run:
  - command: make
  - args: [ install ]
  - inGit:
    - repo: https://github.com/mt-inside/annoying-package
    - ref: v1.2.3
```

**Comment by rawkode** [comment]
I see a couple of potential scenarios here.

1. Auto detect `git` (and other) source locations.

```yaml
- action: command.run:
   command: make
   cwd: git@github.com/rawkode/dotfiles
```

Where `cwd` would be detected as a Git path and a temp clone would be made for the `make` to run.

2. A `build` Action

```yaml
- action: build.make (also build.bazel, build.cargo, etc)
   repository: git@github.com/rawkode/dotfiles
```

Alt:

```yaml
- action: build.custom
   repository: git@github.com/rawkode/dotfiles
   commands:
   - go build
   - go install
```


What do you think?

**Comment by mt-inside** [comment]
I think I'd go with #1, like the auto-detection too. Seems neatest to me, and could be extended to other kinds of remote URL.

To address the other related use cases, I was personally thinking (I raised another issue) about having cargo, `go install` etc modelled as package managers, so I can say
```yaml
- action: package.install
  provider: cargo
  list:
    - procs
    - espanso
```
