### ISSUE TITLE
Feature: various local "install" support

### ISSUE THREAD

**Issue by mt-inside** [comtrya/comtrya#119]
I end up performing certain sets of actions together, eg
* copy a compiled binary to a system path, and strip it (some versions of unix `install` do this)
* copy/template a systemd unit to the right place, `systemctl enable`, `systemctl start`

I know we don't want to be a massive complex system, but it'd be nice to have first-class support for things like this, eg
```yaml
- action: install.systemd_unit
  from: foo.service
  type: <system/user> # copies to /etc/systemd/system or ~/.config/systemd/user
  template: true
```

**Comment by rawkode** [comment]
@mt-inside I'm not entirely sure I understand. Where would this unit file come from?

**Comment by mt-inside** [comment]
Oh I was thiking the user would just supply the unit file, so it'll come from `files/` like a normal `file.copy`. Basically `install.system_unit` would be short-hand for
* `file.copy(files/foo.service, <dst inferred from type field>)`
* `command.run(systemctl daemon-reload)`
* `command.run(systemctl enable foo.service)`
* `command.run(systemctl start foo.service)`

Seem sensible?

**Comment by rawkode** [comment]
Can definitely support this pretty quickly and I wonder what the action API would look like if we could template the unit file in the Comtrya manifest too?

**Comment by mt-inside** [comment]
Yeah that might be quite neat, I was just worried that a higher abstraction would make it harder to go off-piste if a unit needs non-standard settings. But yeah for the happy path we could have something nice and simple like

```yaml
- action: install.systemd_unit
  type: user
  path: /opt/dropbox
```

I just don't know what we do if someone needs to set ExecPre or any of the other million optional settings.
