### ISSUE TITLE
Manifest execution hangs when action is waiting for input

### ISSUE THREAD

**Issue by svallory** [comtrya/comtrya#129]
Homebrew waits for an ENTER key so this manifest hangs: 

```
actions:
  - action: file.download
    from: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    to: tmp/install-brew
    chmod: 775

  - action: command.run
    command: tmp/install-brew
```
