### ISSUE TITLE
Allow skip the whole actions based condition

### ISSUE THREAD

**Issue by theowenyoung** [comtrya/comtrya#196]
For my case, some dotfile is only expected to linux system, for now, I have to check every action by `where: os.name=="linux"`

can we consider some global condition? maybe like:

```yaml
where: os.name=="linux"
actions:
  - action: command.run
    command: echo
```

or:

```yaml
actions:
  - action: skipAll
    where: os.name=="linux"
  - action: command.run
    command: echo

**Comment by Lockszmith-GH** [comment]
I thought about something like this as well. I think the 'more yaml' based approach would be:
You still group it around the actions.

But I would agree, a solution like that would make the code more dynamic

```yaml
actions:
  where: os.name=="linux"
  - action: command.run
    command: echo
```
