### ISSUE TITLE
How to escapse space in path?

### ISSUE THREAD

**Issue by theowenyoung** [comtrya/comtrya#198]
Try to link to vscode settings: `~/Library/Application\ Support/Code/User/settings.json`

```yaml
actions:
  - action: file.link
    source: settins.json
    target: "{{user.home_dir}}/Library/Application\ Support/Code/User/settings.json"
```

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib/src/actions/file/mod.rs:21:14
```

I also tried:

```yaml
actions:
  - action: file.link
    source: settins.json
    target: "{{user.home_dir}}/Library/Application Support/Code/User/settings.json"
```

Same error
