### ISSUE TITLE
Support {{os.hostname}} as variable

### ISSUE THREAD

**Issue by theowenyoung** [comtrya/comtrya#200]
Like this:

```yaml
actions:
    - action: command.run
      command: echo
       where: os.hostname=="test"
```
