### ISSUE TITLE
Feature:  Support Manifest Labels

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#236]
**Description**

Allows manifests to be labeled in such a way that `comtrya -d apply -l setup` could be run and only a subset of the entire manifest directory is applied.

```yaml
labels:
  - setup
  - devtool

actions:
  - ...
```

Perhaps labels should be KV?

```yaml
labels:
  - phase=setup
  - target=devtool

actions:
  - ...
```
