### ISSUE TITLE
Feature: Allow the Default Run to be Configured

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#237]
**Description**

At the moment, `comtrya -d apply` will run EVERY manifest within the manifest directory(ies).

We should provide something inside `Comtrya.yaml` that allows that behaviour to be changed.

```yaml
defaultManifest: dev.tools

# or 

defaultManifests:
  - dev.tools
  - {{ os.family }}
```

And if we build #236, that could/should be a default target:

```yaml
defaultManifests:
  - nameSelector: {{ os.family }}
  - labelSelector:
    - setup
    - devtools

# or 

defaultManifests:
  - nameSelector: {{ os.family }}
  - labelSelector:
       phase: setup
```

**Additional information**
Add more context which didn't fit in the fields above.
