### ISSUE TITLE
Feature: Hooks

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#252]
**Description**

Some mechanism to run a manifest(s) before everything (pre-apply)
Some mechanism to run a manifest(s) after everything  (post-apply)

**Additional information**

I have a manifest for adding homebrew taps, like below. It could be consumed as a dependency, but these style of tasks are really pre-run hooks.

If we support pre-hooks, it's likely there's a use-case for post- and perhaps some others (audit that logs all sudo commands to a text file?)

Food for thought

```yaml
actions:
  - action: package.repository
    provider: homebrew
    name: homebrew/cask

  - action: package.repository
    provider: homebrew
    name: homebrew/cask-versions

  - action: package.repository
    provider: homebrew
    name: homebrew/cask-drivers

```
