### ISSUE TITLE
Feature: Extensions via WASM/WASI

### ISSUE THREAD

**Issue by rawkode** [comtrya/comtrya#263]
**Description**

Dump from our call this evening

```yaml
extensions:
  - ghcr.io/comtrya/comtrya/extensions/echo:latest
    - config.toml
      - atoms
      - actions
    - echo.wasm

manifests:
  action: echo.echo
    string: hello, world
```

I'm sure there's a related issue. @icepuma
