### ISSUE TITLE
Feature: an action to store a fact/variable/context from the output of a command

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#272]
**Description**
Describe the idea / feature request in your own words.

```yml
actions:
  - action: context.set
    command: echo $env:profile
    context: os.user_profile

```

or 

```yml
  - action: cmd.run
    command: echo
    args:
      - "$env:profile"
    stdout:
      context: os.user_profile
```

🤷🏻 

**Additional information**
Add more context which didn't fit in the fields above.

**Comment by airtonix** [comment]
Failing that perhaps there's a way to do this in any value? 

```yml
- action: file.link
  from: profile.ps1
  to: "{{ getEnv('profile') }}"
```

In powershell, `$profile` magically points to : `C:\Users\zenobius\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`

Do we have a way to differentiate between `$env:profile` and `$profile` in powershell? (`$env:profile` is not the same as $profile` btw)
