### ISSUE TITLE
Feature: package.install (provider:winget) sometimes requires additional arguments for automated package install

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#277]
**Description**

For example to install the latest powershell (v7+) comtrya would complete instantly and succesfully. 

```yaml
---
where: os.name == "windows"

actions:

  - action: package.install
    provider: winget
    name: Microsoft.Powershell

```

which is wrong because installing it with : 

```powershell
> winget install --id Microsoft.Powershell --source winget
```

- produces a loading bar
- sometimes requires the user to accept terms and conditions
- (for me) takes quite a while to download, probably because MS are rate limiting the bandwidth on their server.

It wasn't until i switch the action from `package.install` to `command.run` :

```yaml

  - action: command.run
    command: winget
    args:
      - "install --id Microsoft.Powershell --source winget --silent --accept-source-agreements --accept-package-agreements"
```

That I got the expected behaviour.

So perhaps there's two things here: 

- allow `package.install` to accept extra args some how? 
- detect if a package manager is waiting for user input, fail (unless we have a flag i guess) with an error that says something like:

> manifest failed because package manager expected user input, provide arguments to facilitate non interactive installation"

**Additional information**
Add more context which didn't fit in the fields above.
