### ISSUE TITLE
Bug: Tera should only evaluate templates after all where clauses have been analysed

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#283]
**Description**

When I try to evaluate this manifest on linux or macos it fails because it can't find the envvar: 

```
---
where: os.name == "windows"

actions:

  - action: file.copy
    from: winget.json
    to: '{{get_env(name="LOCALAPPDATA", "")}}\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json'

```

on windows `LOCALAPPDATA` is effectively `~/AppData/Local`.

I'm working around this by doing this instead which doesn't cause an error: 

```
---
where: os.name == "windows"

actions:

  - action: file.copy
    from: winget.json
    to: '{{user.home_dir}}\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json'

```

**Steps to reproduce**

```
comtrya -d https://github.com/airtonix/ComtryaProblemRepo#master:tera-evaluates-all-templates-before-where-plan apply
```

**Expected behaviour**
What the expected behaviour in your opinion.

**Environment**
- OS: windows 11
- Version: `0.8.0`

**Additional information**
Add more context which didn't fit in the fields above.
