### ISSUE TITLE
Bug: binary.github prevents further manifest actions from running when it thinks no action is required.

### ISSUE THREAD

**Issue by airtonix** [comtrya/comtrya#287]
**Description**

If I have: 

`files/enact/enact.service`
```
[Unit]
Description=Enact Auto configures Xrandr

[Service]
ExecStart=$HOME/.local/share/bin/enact --pos top --watch
```

`enact.yml`
```yml
---
where: os.name == "linux"

actions:
  - action: binary.github
    name: enact
    directory: "{{ user.home_dir }}/.local/share/bin/"
    repository: chmln/enact
    version: v0.1

  - action: file.copy
    from: enact
    to: "{{ user.home_dir }}/.config/systemd/user/"
```

then: 
- `1st run` both actions run
- `2nd run` binary.github attempts, fails and nothing else in the manifest is processed.

If I switch to:

```yml
---
where: os.name == "linux"

actions:
  - action: file.copy
    from: enact
    to: "{{ user.home_dir }}/.config/systemd/user/"

  - action: binary.github
    name: enact
    directory: "{{ user.home_dir }}/.local/share/bin/"
    repository: chmln/enact
    version: v0.1
```

Then it works.

This would obviously force certain workflows that depend on the installed binary to be split into two manifests.

**Steps to reproduce**

Try the above two manifests.

1. The first one will succeed on first try, never attempt to copy the files on the 2nd try.
2. The second one will always run both actions.

**Expected behaviour**

`binary.github` should never cause the current manifest to bail/error/exit/prevent-further-actions/prevent-further-manifests

**Environment**
- OS: `Fedora release 36 (Thirty Six)` `5.19.15-201.fc36.x86_64`
- Version: `0.8.0`

**Additional information**
Add more context which didn't fit in the fields above.
