### ISSUE TITLE
Feature: OCI artifacts as a source for configs

### ISSUE THREAD

**Issue by icepuma** [comtrya/comtrya#314]
**Description**
Download an OCI artifact similar to the `file.download` - action.

```yaml
action: oci.artifact.download
from: oci://<registry>/<repo>/<artifact-name>
to: /tmp/artifact
```

**Additional information**
This would aid a GitOps way of deploying a machine with an immutable set of config files. The whole thing could be verified by a signature.
