### ISSUE TITLE
Bug: wrongly configured actions are simply ignored, no error shown

### ISSUE THREAD

**Issue by Blizzke** [comtrya/comtrya#318]
**Description**
After being told that you can escalate privileges for a command by using a flag instead of `sudo` as command I initially assumed `privileged: true` would be the way to do so as I couldn't find anything about it in the documentation.

When running `apply` that specific action was just skipped. Turns out it's `sudo: true` instead.

It seems that actions that cannot be parsed or are invalid for some reason are just ignored and no error is given.

**Steps to reproduce**
```
  - action: command.run
    command: cp
    privileged: true
    args:
      - -f
      - manifests/tools/zsh/files/zshenv
      - /etc/zsh/
```

**Expected behaviour**
Getting an error message

**Environment**
- Manjaro
- Version: 0.8.3
