### ISSUE TITLE
Feature: Add support for GPG/PGP encryption

### ISSUE THREAD

**Issue by thebino** [comtrya/comtrya#336]
**Description**
With #56 the support for encryption was added. Instead of using [age](https://crates.io/crates/age) for the encryption itself, I would love to see support for GnuPG/PGP (This could be solved by the [pgp](https://crates.io/crates/pgp) crate

**Additional information**
I'm currently using it with the `command.run` action
```yaml
  - action: command.run
    command: gpg
    args:
      - "--output"
      - "apps/cargo/files/credentials.toml"
      - "--decrypt"
      - "apps/cargo/files/credentials_encrypted.asc"
```
