### ISSUE TITLE
'chmod' option in file.copy

### ISSUE THREAD

**Issue by vielmetti** [comtrya/comtrya#37]
Motiviation: I have a set of little shell scripts that I want to bring down and install. Successful completion of the installation involves setting the execute bit with chmod. In some cases you might also want to install a file, like one that holds a secret, as something other than world-readable.

Suggested concrete syntax:

```
actions:
  - name: setup-tailscale-ubuntu-focal
   action: file.copy
   from: bin/setup-tailscale-ubuntu-focal
   to: /root/.bin/setup-tailscale-ubuntu-focal
   chmod: 700
   template: false
```

Alternatives considered: This is a workaround for #35 where I might be able to install everything with the 'Aptitude' driver. The more general case of `chmod` is a little bit of flexibility to make things just so. Even without the execute bit I can do this bootstrapping phase with `sh -x` so not all is lost.
