### ISSUE TITLE
Bug: homebrew tap is ignored

### ISSUE THREAD

**Issue by thebino** [comtrya/comtrya#424]
**Description**
Trying to install a tap with homebrew but its not installing and the repository is not found in the traces.

**Steps to reproduce**
```
# TUI API Client
# https://github.com/Julien-cpsn/ATAC
actions:
  - action: package.install
    name: atac
    provider: homebrew
    repository: julien-cpsn/atac
```

**Expected behaviour**
atac is being installed

**Environment**
- OS: macOS
- Version: 0.8.8

**Additional information**
https://github.com/Julien-cpsn/ATAC
https://github.com/Julien-cpsn/homebrew-atac

**Comment by rawkode** [comment]
Sorry, this was replaced with a seperate action. We need to update the docs for this.

```yaml
actions:
  - action: package.repository
    provider: homebrew
    name: homebrew/cask-fonts

  - action: package.install
    list:
      - font-cascadia-code
      - font-courgette
      - font-monaspace
      - font-redressed
```


https://github.com/rawkode/rawkode/blob/5c319d44c63225666e23804842fc93723819fba8/dotfiles/fonts.yaml#L4
