### ISSUE TITLE
Bug: `package.install` fails on FreeBSD

### ISSUE THREAD

**Issue by yonas** [comtrya/comtrya#433]
**Description**
Running the `package.install` action on FreeBSD fails with status code 1.

**Steps to reproduce**
```yaml
actions:
  - action: package.install
    list:
    - sd
    - just
```

**Expected behaviour**
Should install without error.

**Environment**
- OS: FreeBSD 14
- Version: 0.8.8
