### ISSUE TITLE
Feature: Support modifying crontab

### ISSUE THREAD

**Issue by yonas** [comtrya/comtrya#473]
**Description**

I'd like to modify any user's crontab.

**Manifest Example**

```yaml
actions:
   - action: cron.add
     - user: some-other-user [ optional ]
     - privileged: true [ if `user` is not the current user, and current user is not `root` ]
     - path:
       - ~/bin [ not sure if this is an append or overwrite to existing `$PATH` ]
       - /some/other/path
     - schedule: 00 00 * * * nvim --headless "+Lazy! sync" +qa
     - schedule:
       - 00 00 * * * my-backup-script1
       - 00 00 * * * my-backup-script2
   - action: cron.remove
     - schedule: ...
     - schedule:
        - ...
        - ...
   - action: cron.list
```

**Comment by martintc** [comment]
Off the top of my head. I tend to run a lot of FreeBSD servers and it would be nice to have a crontab action to do something like add in cron a job for certbot for renewal of LetsEncrypt certs.

If you think an action for `mkinitcpio.conf` is helpful, we cant definitely look into it. Its not a file that I really touch, so I am just not aware of what can be or should be done there. But you can open up an issue with an idea of what a design looks like in a manifest and what it should and should not do and we can go from there. If your interested in implementing it, I can help. I've been putting it off, but I can prioritize writing some developer documentation for writing new actions if that is needed to help.

**Comment by JustinBacher** [comment]
What if, instead of crontab support and mkinitcpio support, add an option called "condition" to command.run.

`condition` being a command that is ran determining whether to perform the command or not

The reason I wanted to add a mkinitcpio action was so I could add nvidia modules to my mkinitcpio without doing it in a script but if we add this we could replace this:

```
nvidia.yaml
---
actions:
  - action: command.run
    command: sh
    args:
    - -c
    - path/of.nvidia.sh

ndivia.sh
---
if [ $(lspci -k | grep -A 2 -E "(VGA|3D)" | grep -i nvidia | wc -l) -gt 0 ]; then
    if [ $(grep 'MODULES=' /etc/mkinitcpio.conf | grep nvidia | wc -l) -eq 0 ]; then
        sudo sed -i "/MODULES=/ s/)$/ nvidia nvidia_modeset nvidia_uvm nvidia_drm)/" /etc/mkinitcpio.conf
    fi
fi
```

With this:

```yaml
- action: command.run
  condition: $(lspci -k | grep -A 2 -E "(VGA|3D)" | grep -i nvidia | wc -l) -gt 0 && $(grep 'MODULES=' /etc/mkinitcpio.conf | grep nvidia | wc -l) -eq 0
  command: sed -i "/MODULES=/ s/)$/ nvidia nvidia_modeset nvidia_uvm nvidia_drm)/" /etc/mkinitcpio.conf
  priviled: true
```

And for the cron job:

```yaml
- action: command.run
  command: crontab -l | { cat; echo "0 0 0 0 0 some entry"; } | crontab -
```

Or just extend the `where` option
