### ISSUE TITLE
Bug: file.unarchive not working

### ISSUE THREAD

**Issue by chad-betamax** [comtrya/comtrya#536]
My comtrya doesn't seem to have unarchiving functionality.

$ comtrya --version
  comtrya 0.9.0

The following manifest generates an error
 ```
actions:
  - action: file.download
    from: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    to: /tmp/neovim.tar.gz

  - action: file.unarchive
    from: /tmp/neovim.tar.gz
    to: /usr/local/bin/
```

With the error looking like this:

>$ comtrya -d manifests apply -m targz_test
>ERROR execute:manifest_load{manifest="test.yaml"}: Manifest 'test' in file with path '/home/chad/manifests/targz_test.yaml' cannot be parsed. Reason: actions.\[1\].action: unknown variant `file.unarchive`, expected one of `command.run`, `directory.copy`, `directory.create`, `file.copy`, `file.download`, `file.link`, `file.remove`, `directory.remove`, `binary.github`, `group.add`, `macos.default`, `package.install`, `package.repository`, `user.add`, `user.group` at line 6 column `13`
