### ISSUE TITLE
Allow overwiting the `files` directory

### ISSUE THREAD

**Issue by Spazzy757** [comtrya/comtrya#96]
## Problem
for actions like `file.copy` and `file.link` allow overwriting the default `files` directory that is required. 

## Reasoning
if for instance, you are migrating from something like `stow` the file structure of your dotfiles is set out with folders like `bash` or `vim`. Comtrya currently requires you to change the structure for your files to be in the structure of `vim/files` and `bash/files` which does not allow for a lot of flexibility in how you want to structure your dotfiles if you could for instance overwrite this variable ate the action level it would allow a lot of people to keep their dotfiles structure and still use Comtrya

example:

```yaml
actions:
- action: file.link
   # Overwrite where to look for file 
   base: bash
   from: .bashrc
   to: {{ user.home_dir }}
```

**Comment by Spazzy757** [comment]
Just a note, currently im getting around this by doing:
```yaml
actions:
  - action: command.run
    command: stow
    dir: .
    args:
      - -v
      - -R
      - -t
      - {{ user.home_dir }}
      - bash/

```
